apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: starry-kids
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend-image
          ports:
            - containerPort: 5173
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          command:
            - "npm"
            - "run"
            - "dev"
