name: Run backend-ci

on:
  pull_request:
    paths:
      - "web/backend/**"
      - ".github/**"

  push:
    branches:
      - main
    paths:
      - "web/backend/**"
      - ".github/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web/backend

    container:
      image: ghcr.io/tatsumi0000/starry-kids/backend:latest

    services:
      db:
        image: mysql:8.1.0
        env:
          TZ: Asia/Tokyo
          MYSQL_ROOT_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            web/backend

      - uses: actions/cache@v3
        with:
          path: /vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path /vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: DB setup
        run: |
          bin/rails db:create

      - name: Run rspec
        run: bundle exec rspec
