version: '3'

services:
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /usr/src/app/backend
    command: 'bin/rails s  -b "0.0.0.0"'
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /usr/src/app/frontend
    command: "npm run dev"
    volumes:
      - ./frontend:/usr/src/app/frontend
    ports:
      - "5173:5173"

volumes:
  db_data:
